name: Codecov

permissions: {}

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'
      - 'release*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codecov:
    runs-on: self-hosted
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            auth.docker.io:443
            codecov.io:443
            eusreplstore*.blob.core.windows.net:443
            ghcr.io:443
            github.com:443
            index.docker.io:443
            jimnotarytest.azurecr.io:443
            objects.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
            proxy.golang.org:443
            sigstore-tuf-root.storage.googleapis.com:443
            sum.golang.org:443
            uploader.codecov.io:443
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup build env
        uses: ./.github/actions/setup-build-env
        with:
          build-cache-key: codecov
      - name: Generate Code Coverage Report
        run: make code-cov-report
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          file: ./coverage.out
          fail_ci_if_error: true
          verbose: true
